# Generated by Django 4.2.1 on 2024-01-31 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('board_id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='게시판ID')),
                ('board_name', models.CharField(max_length=10, verbose_name='게시판이름')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='게시글ID')),
                ('title', models.CharField(max_length=50, verbose_name='글제목')),
                ('content', models.TextField(verbose_name='글내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성시간')),
                ('cmter_size', models.IntegerField(default=0, verbose_name='댓작성자수')),
                ('like_size', models.IntegerField(default=0, verbose_name='좋아요수')),
                ('warn_size', models.IntegerField(default=0, verbose_name='신고수')),
                ('anon_status', models.BooleanField(default=True, verbose_name='익명여부')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='posts.board', verbose_name='게시판')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgfile', models.ImageField(blank=True, null=True, upload_to='', verbose_name='이미지파일')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='posts.post')),
            ],
        ),
    ]
