# Generated by Django 4.2.1 on 2024-02-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='display',
            field=models.BooleanField(default=False, verbose_name='삭제여부'),
        ),
    ]
