# Generated by Django 4.2.1 on 2024-02-09 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
        ('posts', '0005_remove_post_display_alter_image_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='display',
            field=models.BooleanField(default=False, verbose_name='삭제여부'),
        ),
        migrations.AlterField(
            model_name='image',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='posts.post', verbose_name='게시글'),
        ),
        migrations.AlterField(
            model_name='post',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='boards.board', verbose_name='게시판'),
        ),
        migrations.DeleteModel(
            name='Board',
        ),
    ]
