# Generated by Django 4.2.1 on 2024-02-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_display_alter_image_post_alter_post_board_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_profile',
            field=models.IntegerField(default=0, verbose_name='글 프로필 이미지'),
        ),
    ]
