# Generated by Django 4.2.1 on 2024-02-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_author_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='display',
            field=models.BooleanField(default=True, verbose_name='사용자화면'),
        ),
    ]
