# Generated by Django 4.2.1 on 2024-02-10 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0008_alter_post_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='글쓴이'),
        ),
        migrations.AlterField(
            model_name='post',
            name='cmter_size',
            field=models.IntegerField(default=0, verbose_name='댓쓴이수'),
        ),
        migrations.CreateModel(
            name='Commenter',
            fields=[
                ('comment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='댓쓴이ID')),
                ('anon_num', models.IntegerField(verbose_name='익명 번호')),
                ('commenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='댓쓴이')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenters', to='posts.post', verbose_name='게시글')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='게시글ID')),
                ('content', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성시간')),
                ('commenter', models.CharField(max_length=20, verbose_name='댓쓴이')),
                ('like_size', models.IntegerField(default=0, verbose_name='좋아요수')),
                ('warn_size', models.IntegerField(default=0, verbose_name='신고수')),
                ('anon_status', models.BooleanField(default=True, verbose_name='익명여부')),
                ('display', models.BooleanField(default=True, verbose_name='사용자화면')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.post', verbose_name='게시글')),
            ],
        ),
    ]
