# Generated by Django 4.2.1 on 2024-02-10 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_post_author_alter_post_cmter_size_commenter_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commenter',
            old_name='commenter',
            new_name='cmnter',
        ),
        migrations.RenameField(
            model_name='commenter',
            old_name='comment_id',
            new_name='commenter_id',
        ),
    ]
