# Generated by Django 4.2.1 on 2024-02-10 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_rename_commenter_commenter_cmnter_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commenter',
            old_name='cmnter',
            new_name='user',
        ),
    ]
