# Generated by Django 4.2.1 on 2024-02-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_rename_cmnter_commenter_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cmter_size',
        ),
        migrations.AddField(
            model_name='post',
            name='comment_size',
            field=models.IntegerField(default=0, verbose_name='댓글수'),
        ),
    ]
