# Generated by Django 4.2.1 on 2024-02-10 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0013_alter_comment_comment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostLiker',
            fields=[
                ('postliker_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='liker 고유번호')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likers', to='posts.post', verbose_name='게시글')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='like_posts', to=settings.AUTH_USER_MODEL, verbose_name='좋아요 누른 유저')),
            ],
        ),
    ]
