# Generated by Django 4.2.1 on 2024-02-10 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0014_postliker'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentLiker',
            fields=[
                ('commentliker_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='liker 고유번호')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likers', to='posts.comment', verbose_name='댓글')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='like_comments', to=settings.AUTH_USER_MODEL, verbose_name='좋아요 누른 유저')),
            ],
        ),
    ]
