# Generated by Django 4.2.1 on 2024-02-14 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0015_commentliker'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='writer',
            field=models.ForeignKey(default=uuid.UUID('51b6cb41-759f-4966-9f10-8028eafbb22f'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='댓쓴이'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commenter',
            field=models.CharField(max_length=20, verbose_name='댓쓴이 표시 이름'),
        ),
        migrations.AlterField(
            model_name='commenter',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commented_posts', to=settings.AUTH_USER_MODEL, verbose_name='댓쓴이'),
        ),
    ]
