# Generated by Django 4.2.1 on 2024-02-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_alter_comment_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='up_comment',
            field=models.UUIDField(blank=True, default=None, null=True, verbose_name='어미 댓글'),
        ),
    ]
