# Generated by Django 4.2.1 on 2024-02-19 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_comment_up_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='up_comment',
            new_name='up_comment_id',
        ),
    ]
