# Generated by Django 4.2.1 on 2024-03-01 18:27

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_rename_up_comment_comment_up_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='imgfile',
            field=models.ImageField(blank=True, null=True, upload_to=posts.models.Image.image_upload_path, verbose_name='이미지파일'),
        ),
    ]
