# Generated by Django 4.2.1 on 2024-02-15 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('인증대기', '인증대기'), ('사생인증', '사생인증'), ('정지', '정지'), ('학생회', '학생회'), ('관리자', '관리자')], default=('인증대기', '인증대기'), max_length=255, verbose_name='사용자 권한'),
        ),
    ]
