# Generated by Django 4.2.1 on 2024-02-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='suspension_end_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='정지 종료일'),
        ),
    ]
