# Generated by Django 4.2.1 on 2024-02-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_suspension_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(default='인증대기', max_length=255, verbose_name='사용자 권한'),
        ),
    ]
