# Generated by Django 4.2.1 on 2024-02-19 08:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_email_alter_user_nickname_alter_user_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedUser',
            fields=[
                ('deleted_user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='고유번호')),
                ('name', models.CharField(max_length=30, verbose_name='이름')),
                ('email', models.EmailField(max_length=255, verbose_name='이메일')),
                ('room', models.PositiveSmallIntegerField(verbose_name='호실수')),
                ('school', models.CharField(max_length=255, verbose_name='학교')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=255, verbose_name='닉네임'),
        ),
        migrations.AlterField(
            model_name='user',
            name='room',
            field=models.PositiveSmallIntegerField(verbose_name='호실수'),
        ),
    ]
