# Generated by Django 4.2.1 on 2024-02-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_emailvarify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailvarify',
            name='code',
            field=models.CharField(max_length=6, verbose_name='인증번호'),
        ),
    ]
