# Generated by Django 4.2.1 on 2024-02-20 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_emailvarify_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('notice_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='고유번호')),
                ('root_id', models.UUIDField(verbose_name='루트 객체 uuid')),
                ('category', models.CharField(max_length=30, verbose_name='알림 카테고리')),
                ('noticed_at', models.DateTimeField(auto_now_add=True, verbose_name='알림 날짜')),
                ('checked', models.BooleanField(default=False, verbose_name='확인 여부')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
        ),
    ]
