# Generated by Django 4.2.1 on 2024-02-22 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_notice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='noticed_at',
            new_name='created_at',
        ),
    ]
