# Generated by Django 4.2.1 on 2024-02-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_room_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='room_card',
            field=models.ImageField(upload_to='', verbose_name='호실카드 사진'),
        ),
    ]
