# Generated by Django 4.2.1 on 2024-03-01 18:27

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_user_room_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=255, unique=True, verbose_name='닉네임'),
        ),
        migrations.AlterField(
            model_name='user',
            name='room_card',
            field=models.ImageField(upload_to=users.models.User.image_upload_path, verbose_name='호실카드 사진'),
        ),
    ]
