# Generated by Django 4.2.1 on 2024-04-08 06:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_nickname_alter_user_room_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='deleteduser',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='탈퇴 날짜'),
        ),
    ]
