# Generated by Django 4.2.1 on 2024-02-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('board_id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='게시판ID')),
                ('board_name', models.CharField(max_length=10, verbose_name='게시판이름')),
            ],
        ),
    ]
