# Generated by Django 4.2.1 on 2024-02-15 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='board_id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='게시판ID'),
        ),
    ]
