# Generated by Django 4.2.1 on 2024-03-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_alter_board_board_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='board_name',
            field=models.CharField(max_length=50, verbose_name='게시판이름'),
        ),
    ]
