# Generated by Django 4.2.1 on 2024-02-07 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomrequest',
            name='request_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='신청날짜'),
        ),
        migrations.AlterField(
            model_name='roomrequest',
            name='status',
            field=models.IntegerField(choices=[(0, '신청완료'), (1, '처리완료')], default=0, verbose_name='처리상태'),
        ),
    ]
