# Generated by Django 4.2.1 on 2024-02-19 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrators', '0002_alter_roomrequest_request_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrozenHistory',
            fields=[
                ('frozen_history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='고유번호')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='정지처리 날짜')),
                ('end_date', models.DateTimeField(verbose_name='정지 풀리는 날짜')),
                ('days', models.IntegerField(verbose_name='정지 날 수')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='정지자')),
            ],
        ),
    ]
