# Generated by Django 4.2.1 on 2024-02-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0004_rename_frozenhistory_freezehistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freezehistory',
            name='complained_size',
            field=models.IntegerField(default=0, verbose_name='청산 신고수'),
        ),
    ]
