# Generated by Django 4.2.1 on 2024-02-22 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0005_freezehistory_complained_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomrequest',
            old_name='request_date',
            new_name='created_at',
        ),
    ]
