# Generated by Django 4.2.1 on 2024-02-22 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0006_rename_request_date_roomrequest_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freezehistory',
            old_name='start_date',
            new_name='created_at',
        ),
    ]
