# Generated by Django 4.2.1 on 2024-02-18 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0017_alter_comment_writer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('complain_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='신고ID')),
                ('comp_date', models.DateField(auto_now_add=True, verbose_name='신고날짜')),
                ('category', models.CharField(choices=[('불건전한 내용', '불건전한 내용'), ('사기', '사기'), ('상업적 광고', '상업적 광고'), ('특정인에 대한 비난', '특정인에 대한 비난'), ('도배', '도배'), ('기타', '기타')], max_length=50, verbose_name='신고사유')),
                ('status', models.IntegerField(choices=[(0, '대기중'), (1, '처리됨')], default=0, verbose_name='신고처리상태')),
                ('comp_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.comment', verbose_name='신고 댓글')),
                ('comp_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.post', verbose_name='신고 게시글')),
                ('comp_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='신고자')),
                ('comped_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complains', to=settings.AUTH_USER_MODEL, verbose_name='피신고자')),
            ],
        ),
    ]
