# Generated by Django 4.2.1 on 2024-02-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complains', '0002_alter_complain_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='status',
            field=models.CharField(choices=[(0, '대기중'), (1, '처리됨')], default=(0, '대기중'), max_length=30, verbose_name='신고처리상태'),
        ),
    ]
