# Generated by Django 4.2.1 on 2024-02-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complains', '0005_alter_complain_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='status',
            field=models.CharField(choices=[('신고접수', '신고접수'), ('처리완료', '처리완료')], default='신고접수', max_length=30, verbose_name='신고처리상태'),
        ),
    ]
