# Generated by Django 4.2.1 on 2024-02-22 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complains', '0008_rename_comp_date_complain_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complain',
            name='created_at',
        ),
    ]
