# Generated by Django 4.2.1 on 2024-02-22 18:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('complains', '0009_remove_complain_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='신고날짜'),
        ),
    ]
