# Generated by Django 4.2.1 on 2024-04-11 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_alter_image_imgfile'),
        ('complains', '0011_alter_complain_comp_comment_alter_complain_comp_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='comp_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.comment', verbose_name='신고 댓글'),
        ),
        migrations.AlterField(
            model_name='complain',
            name='comp_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.post', verbose_name='신고 게시글'),
        ),
    ]
